name: mehonot_admin
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.1
  flutter_easylogger: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  readmore: ^2.2.0
  dotted_border: ^2.0.0+2
  animated_bottom_navigation_bar: ^1.1.0
  flutter_multi_formatter: ^2.8.0
  flutter_barcode_scanner: ^2.0.0
  flutter_svg: ^1.1.5
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  flutter_secure_storage: ^6.0.0
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  heroicons: ^0.7.0
  dropdown_button2: ^1.8.9
  retrofit: ^3.3.1
  carousel_slider: ^4.1.1
  flutter_slidable: ^2.0.0
  lottie: ^1.4.3
  uuid: ^3.0.7
  encrypt: ^5.0.1
  fluttertoast: ^8.2.1
  intl: ^0.18.0
  mask_text_input_formatter: ^2.4.0
  intro_slider: ^4.2.0
  auto_route: ^7.1.0
  shimmer: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  flutter_image_compress: ^2.0.3
  image_cropper: ^4.0.1
  url_launcher: ^6.1.11
  webview_flutter: ^3.0.3
  connectivity_plus: ^4.0.1
  share_plus: ^7.0.2
  flutter_quill: ^7.2.9
  flutter_keyboard_visibility: ^5.4.1

  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.3
  hive_generator: ^2.0.0
  json_annotation: ^4.8.0
  auto_route_generator: ^7.0.0

#First configure flutter_intl
flutter_intl:
  enabled: true
  class_name: "AppIntl" # Class name which is used in by the client, default "S"
  arb_dir: "lib/l10n"
  main_locale: "en" # main locale, default "en"
  output_dir: "lib/generated/rf_fit" # Generated i10n files location

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: PoppinsThin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
